version: 2
root-markers:
  - .git/
lint-debounce: 0.5s
format-debounce: 0.25s
tools:
  lua-lua-format: &lua-lua-format
    format-command: "lua-format -i"
    format-stdin: true

  prettierd: &prettier
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  ts-eslint: &ts-eslint
    lint-command: "eslint -f visualstudio --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %trror %m"

  md-markdownlint: &md-markdownlint
    lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  md-pandoc: &md-pandoc
    format-command: "pandoc -f markdown -t gfm -sp --tab-stop=2"

  cspell-lint: &cspell-lint
    prefix: cspell
    lint-severity: 4
    lint-command: "npx --no-install cspell lint --no-progress --no-summary --no-color ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c - %m"
      - "%f:%l:%c %m"
    root-markers:
      - package.json
      - .cspell.json
      - cspell.json
      - .cSpell.json
      - cSpell.json
      - cspell.config.js
      - cspell.config.cjs
      - cspell.config.json
      - cspell.config.yaml
      - cspell.config.yml
      - cspell.yaml
      - cspell.yml
languages:
  css:
    - <<: *prettier
  html:
    - <<: *prettier
  javascript:
    - <<: *ts-eslint
    - <<: *prettier
  typescript:
    - <<: *ts-eslint
    - <<: *prettier
  json:
    - <<: *prettier
  lua:
    - <<: *lua-lua-format
  markdown:
    - <<: *md-markdownlint
    - <<: *md-pandoc
    - <<: *prettier
  yaml:
    - <<: *prettier
    - <<: *cspell-lint
  =:
    - <<: *cspell-lint
