---
version: 2
root-markers:
  - .git/
lint-debounce: 0.5s
format-debounce: 0.25s
tools:
  lua-format: &lua-format
    format-command: "lua-format -i"
    format-stdin: true

  prettierd: &prettier
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  eslint: &eslint
    prefix: eslint
    lint-command: "npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json
    commands:
      - title: "eslint fix"
        command: npx
        arguments:
          - "--no-install"
          - "eslint"
          - "--fix"
          - "${INPUT}"

  yamllint: &yamllint
    prefix: yamllint
    lint-command: "yamllint --strict --format parsable ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: [%t%*[a-z]] %m"
    env:
      - "PYTHONIOENCODING=UTF-8"

  markdownlint: &markdownlint
    lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  pandoc: &pandoc
    format-command: "pandoc -f markdown -t gfm -sp --tab-stop=2"

  cspell: &cspell
    prefix: cspell
    lint-severity: 4
    lint-command: "npx --no-install cspell lint --no-progress --no-summary --no-color ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c - %m"
      - "%f:%l:%c %m"
    root-markers:
      - package.json
      - .cspell.json
      - cspell.json
      - .cSpell.json
      - cSpell.json
      - cspell.config.js
      - cspell.config.cjs
      - cspell.config.json
      - cspell.config.yaml
      - cspell.config.yml
      - cspell.yaml
      - cspell.yml
languages:
  css:
    - <<: *prettier
  html:
    - <<: *prettier
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
  lua:
    - <<: *lua-format
  markdown:
    - <<: *markdownlint
    - <<: *pandoc
    - <<: *prettier
  yaml:
    - <<: *yamllint
    - <<: *prettier
  =:
    - <<: *cspell
